package eu.kanade.tachiyomi.extension.ar.mangapro;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class mipmap {
        public static final int ic_launcher = 0x7f010000;
    }
}
